default_language_version:
  python: python3.12

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.1
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 1.3.1
  hooks:
  - id: tox-ini-fmt

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    pass_filenames: false
    args: ["src", "--config-file", "pyproject.toml"]
    additional_dependencies:
    - pytest>=7.1
    - keyring>=24.2

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff
    args: [--exit-non-zero-on-fix]
    types_or: [ python, pyi ]
  - id: ruff-format
    args: [--exit-non-zero-on-fix]
    types_or: [ python, pyi ]
