[tox]
requires =
    tox>=4.2
env_list =
    py314
    py313
    py312
    py311
    py310
    py39
    py38
    type

[testenv]
skip_install = true
pass_env =
    DBUS_SESSION_BUS_ADDRESS
    DISPLAY
    WAYLAND_DISPLAY
commands_pre =
    uv sync --active --group dev
commands =
    uv run --active pytest tests
allowlist_externals =
    uv

[testenv:type]
skip_install = true
commands_pre =
    uv sync --active --group dev
commands =
    uv run --active mypy src
allowlist_externals =
    uv
